### ISSUE TITLE
FatRat mono-Denvelop utils [common issue]

### ISSUE THREAD

**Issue by Jsimpki** [Screetsec/TheFatRat#355]
SO, I saw a lot of your related issues on this and followed the steps. I even put the repos on Parrot OS. 

list of Repos 

deb http://http.kali.org/kali kali-rolling main contrib non-free
deb-src http://http.kali.org/kali kali-rolling main contrib non-free
deb http://old.kali.org/kali sana main non-free contrib
deb-src http://old.kali.org/kali sana main non-free contrib

It also gives me a list of dependencies that aren't met, It seems that the repos that you recommended for other people aren't the solution for the install, at least not for Parrot OS. If you need any other Screen prints Ill be more than happy to help out
As you can see the Updated version still askes for Mono-develop Utils
![image](https://user-images.githubusercontent.com/20587881/58364580-40d11700-7e7c-11e9-96d6-bb057bb495f8.png)

This version was 'git cloned'd straight from your directory here on github

**Comment by Jsimpki** [comment]
You'll need to zoom in as the color is blue on black.

**Comment by peterpt** [comment]
The problem is that fatrat is not using kali repository to install mono-mcs but your original repository .

Here is is one thing that you all here should know :

Fatrat uses kali repositories just to install some tools that by default are not in the conventional repositories , such as "backdoor factory , metasploit-framework , searchsploit & a few more" these tools are for pentest distributions and by default the conventional parrot , debian , ubuntu do not have these tools or they are not maintained regularly in their repositories , this is why we use kali to install those tools .

Add this repository to your sources.list

deb http://deb.debian.org/debian stretch main contrib non-free
deb-src http://deb.debian.org/debian stretch main contrib non-free

Then run apt-get update & run setup.sh from fatrat

when finished then delete those lines from your sources.list and run this command :

apt-get clean && apt-get clean cache && apt-get update 

and finally run setup.sh from fatrat

after instalation

**Comment by Jsimpki** [comment]
I'm giving this a shot right now. I hope this solves it.

**Comment by Jsimpki** [comment]
Okay that didnt solve the issue. It still calls for it saying Not OK

**Comment by darshanup** [comment]
Mine tool dependencies aren't installed.

**Comment by suh004757** [comment]
use official repository for kali in official site 
add 
deb http://http.kali.org/kali kali-rolling main non-free contrib
deb-src https://http.kali.org/kali kali-rolling main non-free contrib

**Comment by AmanTyagi2432** [comment]
it is not working.
plzz help me @peterpt 
![Screenshot from 2019-07-14 15-44-07](https://user-images.githubusercontent.com/52859453/61182257-6abde300-a64e-11e9-887a-4ccc04cc9d10.png)

**Comment by bilalmehrban** [comment]
![image](https://user-images.githubusercontent.com/17435774/61228052-ef882a00-a73e-11e9-9d81-8a02df1a18a2.png)
![image](https://user-images.githubusercontent.com/17435774/61228101-062e8100-a73f-11e9-82d8-3b9c069c8295.png)
All the methods that you specified are not working. I have even tried installing a clean os.

**Comment by bilalmehrban** [comment]
@peterpt  May there is an issue in fatRat.

**Comment by peterpt** [comment]
you all that have issues installing monodenvelop utils put the debian repositories in your sources.list 

deb http://deb.debian.org/debian stretch main contrib non-free
deb-src http://deb.debian.org/debian stretch main contrib non-free

and then write this :

apt-get clean && apt-get update

then write this in your terminal :

apt-cache search mono-mcs 

and put here the print screen for me to see

**Comment by bilalmehrban** [comment]
![image](https://user-images.githubusercontent.com/17435774/61240284-4a7b4a80-a75a-11e9-8035-d21d23c7ea00.png)
![image](https://user-images.githubusercontent.com/17435774/61241491-089fd380-a75d-11e9-9eef-3d7cf1a8836d.png)
![image](https://user-images.githubusercontent.com/17435774/61241547-279e6580-a75d-11e9-9202-b29140a0dad4.png)

**Comment by bilalmehrban** [comment]
@peterpt I have posted all three screenshots do have a look on these.

**Comment by Lucas03lescure** [comment]
having the same issue but with Nethunter, under Mono-Develop Utils -> not found! 
i have
 Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formated in this environment.
You may get a more descriptive message by running the program as non-root user or by removing the suid bit on the executable
xterm: Xt error: can't open display: %s
xterm: DISPLAY is not set

**Comment by peterpt** [comment]
Write 'apt-get install mono-mcs' and post here the print screen

**Comment by bilalmehrban** [comment]
> Write 'apt-get install mono-mcs' and post here the print screen

![image](https://user-images.githubusercontent.com/17435774/61295564-be1c6680-a7f1-11e9-829c-401f6c07cc07.png)

Installation was successful no error there. 
I also verified it.
![image](https://user-images.githubusercontent.com/17435774/61297141-05582680-a7f5-11e9-8030-1e06b884efaa.png)

**Comment by Lucas03lescure** [comment]
> Write 'apt-get install mono-mcs' and post here the print screen

it fixed mono-denvelop utils but not wingw-32 and wingw-w64

**Comment by Lucas03lescure** [comment]
thnx worked

**Comment by bilalmehrban** [comment]
> thnx worked

Oh good is mono develop installed now?

**Comment by Lucas03lescure** [comment]
Yeah, after it installed i added old.kali.org in /etc/apt/sources.list 
did : apt-get update 
then: apt-get install mingw32 (and mingw-w64)
removed the old.kali.org from the sources.list 
apt-get update
and done

**Comment by bilalmehrban** [comment]
> Yeah, after it installed i added old.kali.org in /etc/apt/sources.list
> did : apt-get update
> then: apt-get install mingw32 (and mingw-w64)
> removed the old.kali.org from the sources.list
> apt-get update
> and done
> 
> check if it's installed, do ./setup once more

For me after following the steps of @peterpt  I ran the FatRat installation and mono develop was installed this time.

**Comment by Lucas03lescure** [comment]
yeah it worked

**Comment by lowuser-mian** [comment]
I'm still having the problem while installing mono-denvelop utils
![Screenshot from 2019-08-03 00-22-38](https://user-images.githubusercontent.com/53163192/62375514-14acd300-b55c-11e9-8e00-051e7389e861.png)

**Comment by peterpt** [comment]
lowuser-mian , that is happenign because you update your repository lists and did not yet upgraded your system , or that reference is only in apt cache .
run "apt-get clean && apt-get clean cache && apt-get update" , then check if package is still in repository , in case not then downgrade your repositories and install the package from there .

**Comment by lowuser-mian** [comment]
Thanks for your reply....
I have installed TheFatRat...
Regards

**Comment by r00tali** [comment]
i fixed the issue using, APT INSTALL MONO-MCS , no fuss

**Comment by madodamusic** [comment]
i fixed by install 
apt-get install mono-complete

**Comment by ateeqmughal266** [comment]
still getting "Mono-Denvelop Utils -> Not OK" error and none of the above steps worked for me!
help please.
Thanks in advance!

**Comment by peterpt** [comment]
apt-get remove --purge monodevelop
The problem is that you have one more recent version from monodevelop installed in your system , and you are pointing the mono-mcs from stretch to be installed witch is not compatible with that version .
Using your normal repositories you should see if you have mono-mcs and mono-devel in your current repositories , in case not then remove the full monodevelop from your system and use the stretch repo to install both packages .

with : apt-cache policy monodevelop or mono-mcs or mono-devel you can see witch version is or not installed and from witch repository .

btw , dont revive old topics .
