### ISSUE TITLE
Do you want to exit - issue

### ISSUE THREAD

**Issue by Kaicastledine** [Screetsec/TheFatRat#99]
Hello,

Regardless to if you  Type  (Yes or No)  the program exits anyway ?

Version 1.9.3 - fresh install 
Running Kali

**Comment by peterpt** [comment]
yup , you are right , that happens specifically in msvenom menu , i have detected where is the error .
I will not patch right now the fatrat script because i am fixing also other code errors in the script .
On next weekend we will update the script to fix that error and other stuff .

**Comment by peterpt** [comment]
Fixed , just write ./update in your fatrat folder and you will be updated with the new patch .

**Comment by Kaicastledine** [comment]
Thanks for taking a look at this.

Still getting the Exit regardless issue  - Tested on MSFvenom PHP payload gen.

Let me know if I can do any other testing to help etc.

**Comment by peterpt** [comment]
Everything is fine around here .
do this on terminal insie your fatrat folder : 
rm update
wget https://raw.githubusercontent.com/Screetsec/TheFatRat/master/update
chmod +x update
./update

**Comment by Kaicastledine** [comment]
Still getting the issue here after replacing the update.
Tested again on the MSF PHP gen payload.

**Comment by peterpt** [comment]
look , everything is working at it should be .
https://www.youtube.com/watch?v=TJ4-HcxFcbA

eventually the update script is not working as is should be .
I will check it later .

remove the fatrat script and pick up the raw file from git .
in fatrat folder : 

rm fatrat
wget https://raw.githubusercontent.com/Screetsec/TheFatRat/master/fatrat
chmod +x fatrat

**Comment by Kaicastledine** [comment]
Can Now see the change to 

"Press any key to return to menu"

This works nicely, thank you.
